### ISSUE TITLE
Translation Reviewer adding/removing

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/FTB-Wiki-Issue-Tracker#7]
People cannot be removed from the Translation Reviewer group. Sysops should be able to do this.

**Comment by Telshin** [comment]
Should be fixed

**Comment by retep998** [comment]
I am a sysop and I am unable to remove people from the Translation Reviewer group.

**Comment by elifoster** [comment]
@Telshin You did not fix it http://puu.sh/eaHmn/0d81f03028.png

**Comment by Telshin** [comment]
Alrighty. We'll have to see why the custom groups are still misbehaving.
Thanks!

**Comment by Alexia** [comment]
The FlaggedRevs code by default limits sysops(Adminstrators) to only add or remove the editor and autoreview groups.  Unfortunately this is very over reaching on the part of the FlaggedRevs extension code base since it prevents normal sysop group functionality.  We can simply nuke these lines from FlaggedRevs.config.php.  Would that be fine?

# Special:Userrights settings

# # Basic rights for Sysops

$wgAddGroups['sysop'][] = 'editor'; // promote to basic reviewer (established editors)
$wgRemoveGroups['sysop'][] = 'editor'; // demote from basic reviewer (established editors)
$wgAddGroups['sysop'][] = 'autoreview'; // promote to basic auto-reviewer (semi-trusted users)
$wgRemoveGroups['sysop'][] = 'autoreview'; // demote from basic auto-reviewer (semi-trusted users)

**Comment by elifoster** [comment]
I'm not sure what this has to do with the Translate extension.

**Comment by noahm** [comment]
Disregard previous FlaggedRevs comment. The issue should now be completely resolved as of 5 minutes ago.

**Comment by elifoster** [comment]
Indeed it is.
